In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('loan_approval.csv') # load the dataset into a pandas dataframe

In [3]:
df

,name,city,income,credit_score,loan_amount,years_employed,points,loan_approved
0,Allison Hill,East Jill,113810,389,39698,27,50.0,False
1,Brandon Hall,New Jamesside,44592,729,15446,28,55.0,False
2,Rhonda Smith,Lake Roberto,33278,584,11189,13,45.0,False
3,Gabrielle Davis,West Melanieview,127196,344,48823,29,50.0,False
4,Valerie Gray,Mariastad,66048,496,47174,4,25.0,False
...,...,...,...,...,...,...,...,...
1995,James Schaefer,Robertton,92163,770,12251,13,85.0,True
1996,Diana Lin,New Frank,38799,635,48259,17,40.0,False
1997,Brandon Meyer,East Haley,41957,763,16752,5,60.0,True
1998,Jason Price,Adamland,139022,360,24031,35,55.0,False
1999,Nicole Brown,New Nathantown,41188,482,31397,6,20.0,False

In [4]:
df.drop(['name','city'], axis=1, inplace=True)  # drop name and city columns parmanently

In [5]:
df

      income  credit_score  loan_amount  years_employed  points  loan_approved
0     113810           389        39698              27    50.0          False
1      44592           729        15446              28    55.0          False
2      33278           584        11189              13    45.0          False
3     127196           344        48823              29    50.0          False
4      66048           496        47174               4    25.0          False
...      ...           ...          ...             ...     ...            ...
1995   92163           770        12251              13    85.0           True
1996   38799           635        48259              17    40.0          False
1997   41957           763        16752               5    60.0           True
1998  139022           360        24031              35    55.0          False
1999   41188           482        31397               6    20.0          False

[2000 rows x 6 columns]

In [6]:
df['loan_approved'].unique() # check the unique values in loan_approved column

array([False,  True])

In [7]:
loan_approved_dict={True:1, False:0} # create a dictionary to map the values of loan_approved column

In [8]:
df['loan_approved']=df['loan_approved'].map(loan_approved_dict) # map the values of loan_approved column using the dictionary

In [9]:
df['loan_approved'].unique() # check the unique values in loan_approved column after mapping

array([0, 1])

In [10]:
df # check the updated dataframe

      income  credit_score  loan_amount  years_employed  points  loan_approved
0     113810           389        39698              27    50.0              0
1      44592           729        15446              28    55.0              0
2      33278           584        11189              13    45.0              0
3     127196           344        48823              29    50.0              0
4      66048           496        47174               4    25.0              0
...      ...           ...          ...             ...     ...            ...
1995   92163           770        12251              13    85.0              1
1996   38799           635        48259              17    40.0              0
1997   41957           763        16752               5    60.0              1
1998  139022           360        24031              35    55.0              0
1999   41188           482        31397               6    20.0              0

[2000 rows x 6 columns]

In [11]:
x=df.drop(['loan_approved'],axis=1) # drop the points column and store in x variable

In [12]:
x

      income  credit_score  loan_amount  years_employed  points
0     113810           389        39698              27    50.0
1      44592           729        15446              28    55.0
2      33278           584        11189              13    45.0
3     127196           344        48823              29    50.0
4      66048           496        47174               4    25.0
...      ...           ...          ...             ...     ...
1995   92163           770        12251              13    85.0
1996   38799           635        48259              17    40.0
1997   41957           763        16752               5    60.0
1998  139022           360        24031              35    55.0
1999   41188           482        31397               6    20.0

[2000 rows x 5 columns]

In [13]:
y=df['loan_approved'] # store the points column in y variable

In [14]:
y

0       0
1       0
2       0
3       0
4       0
       ..
1995    1
1996    0
1997    1
1998    0
1999    0
Name: loan_approved, Length: 2000, dtype: int64