In [65]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [66]:
df=pd.read_csv(r'C:\Users\rehan\OneDrive\Desktop\Data Science\6-Months-Data-Science\machine Learning\bike project\data\Used_Bikes.csv')

In [67]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [68]:
df.drop(['bike_name','city'], axis=1, inplace=True)

In [69]:
df

          price  kms_driven        owner   age  power          brand
0       35000.0     17654.0  First Owner   3.0  110.0            TVS
1      119900.0     11000.0  First Owner   4.0  350.0  Royal Enfield
2      600000.0       110.0  First Owner   8.0  675.0        Triumph
3       65000.0     16329.0  First Owner   4.0  180.0            TVS
4       80000.0     10000.0  First Owner   3.0  150.0         Yamaha
...         ...         ...          ...   ...    ...            ...
32643   39000.0     22000.0  First Owner   4.0  100.0           Hero
32644   30000.0      6639.0  First Owner   9.0  180.0            TVS
32645   60000.0     20373.0  First Owner   6.0  220.0          Bajaj
32646   15600.0     84186.0  First Owner  16.0  125.0           Hero
32647   22000.0     60857.0  First Owner  13.0  150.0          Bajaj

[32648 rows x 6 columns]

In [70]:
owner_dict={'First Owner':1,'Second Owner':2,'Third Owner':3,'Fourth Owner':4,'Fifth Owner':5,'Sixth Owner':6,'Seventh Owner':7,'Eighth Owner':8,'Ninth Owner':9,'Tenth Owner':10}
df['owner']=df['owner'].map(owner_dict)

In [71]:
df

          price  kms_driven  owner   age  power          brand
0       35000.0     17654.0    1.0   3.0  110.0            TVS
1      119900.0     11000.0    1.0   4.0  350.0  Royal Enfield
2      600000.0       110.0    1.0   8.0  675.0        Triumph
3       65000.0     16329.0    1.0   4.0  180.0            TVS
4       80000.0     10000.0    1.0   3.0  150.0         Yamaha
...         ...         ...    ...   ...    ...            ...
32643   39000.0     22000.0    1.0   4.0  100.0           Hero
32644   30000.0      6639.0    1.0   9.0  180.0            TVS
32645   60000.0     20373.0    1.0   6.0  220.0          Bajaj
32646   15600.0     84186.0    1.0  16.0  125.0           Hero
32647   22000.0     60857.0    1.0  13.0  150.0          Bajaj

[32648 rows x 6 columns]

In [72]:
brand_dict={'Royal Enfield':1,'Bajaj':2,'Honda':3,'TVS':4,'Hero':5,'Yamaha':6,'Suzuki':7,'KTM':8,'Harley Davidson':9,'Kawasaki':10,'Ducati':11,'Benelli':12,'Triumph':13,'BMW':14,'Jawa':15}
df['brand']=df['brand'].map(brand_dict)

In [73]:
df

          price  kms_driven  owner   age  power  brand
0       35000.0     17654.0    1.0   3.0  110.0    4.0
1      119900.0     11000.0    1.0   4.0  350.0    1.0
2      600000.0       110.0    1.0   8.0  675.0   13.0
3       65000.0     16329.0    1.0   4.0  180.0    4.0
4       80000.0     10000.0    1.0   3.0  150.0    6.0
...         ...         ...    ...   ...    ...    ...
32643   39000.0     22000.0    1.0   4.0  100.0    5.0
32644   30000.0      6639.0    1.0   9.0  180.0    4.0
32645   60000.0     20373.0    1.0   6.0  220.0    2.0
32646   15600.0     84186.0    1.0  16.0  125.0    5.0
32647   22000.0     60857.0    1.0  13.0  150.0    2.0

[32648 rows x 6 columns]

In [74]:
# drop duplicate values from the dataset
df.drop_duplicates(inplace=True)

In [75]:
# drop the null values from the dataset
df.dropna(inplace=True)

In [76]:
print("total duplicate values in data : ",df.duplicated().sum())
print("total null values in data : ",df.isnull().sum())

total duplicate values in data :  0
total null values in data :  price         0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [77]:
df

         price  kms_driven  owner  age  power  brand
0      35000.0     17654.0    1.0  3.0  110.0    4.0
1     119900.0     11000.0    1.0  4.0  350.0    1.0
2     600000.0       110.0    1.0  8.0  675.0   13.0
3      65000.0     16329.0    1.0  4.0  180.0    4.0
4      80000.0     10000.0    1.0  3.0  150.0    6.0
...        ...         ...    ...  ...    ...    ...
9361   50000.0     29134.0    1.0  7.0  220.0    2.0
9362   25000.0     48587.0    1.0  8.0  150.0    5.0
9369   35000.0     60000.0    1.0  9.0  220.0    2.0
9371  139000.0     21300.0    1.0  4.0  400.0    2.0
9372   80000.0      7127.0    1.0  5.0  220.0    2.0

[7094 rows x 6 columns]

In [78]:
# df.to_csv("clean_bike_data.csv")

In [79]:
df=pd.read_csv("clean_bike_data.csv")

In [80]:
df.drop(columns=['Unnamed: 0'], inplace=True)

In [81]:
x=df.drop('price',axis=1)
y=df[['price']]

In [82]:
x

      kms_driven  owner  age  power  brand
0        17654.0    1.0  3.0  110.0    4.0
1        11000.0    1.0  4.0  350.0    1.0
2          110.0    1.0  8.0  675.0   13.0
3        16329.0    1.0  4.0  180.0    4.0
4        10000.0    1.0  3.0  150.0    6.0
...          ...    ...  ...    ...    ...
7089     29134.0    1.0  7.0  220.0    2.0
7090     48587.0    1.0  8.0  150.0    5.0
7091     60000.0    1.0  9.0  220.0    2.0
7092     21300.0    1.0  4.0  400.0    2.0
7093      7127.0    1.0  5.0  220.0    2.0

[7094 rows x 5 columns]

In [83]:
y

         price
0      35000.0
1     119900.0
2     600000.0
3      65000.0
4      80000.0
...        ...
7089   50000.0
7090   25000.0
7091   35000.0
7092  139000.0
7093   80000.0

[7094 rows x 1 columns]

In [84]:
import sklearn

In [85]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [86]:
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(5675, 5) (1419, 5) (5675, 1) (1419, 1)

In [87]:
x_train

      kms_driven  owner   age  power  brand
794      15059.0    1.0   3.0  100.0    2.0
6355     38000.0    1.0  16.0  100.0    5.0
3658     32000.0    1.0   5.0  180.0    4.0
4793     10000.0    1.0   3.0  100.0    5.0
2094     22113.0    1.0  18.0  100.0    5.0
...          ...    ...   ...    ...    ...
3772     35020.0    1.0   5.0  150.0    2.0
5191      5120.0    1.0   3.0  100.0    5.0
5226     22405.0    1.0   5.0  100.0    5.0
5390     28864.0    3.0   8.0  150.0    6.0
860      20000.0    1.0   4.0  250.0    6.0

[5675 rows x 5 columns]

In [88]:
y_train

         price
794    30000.0
6355   19000.0
3658   59900.0
4793   45000.0
2094   25000.0
...        ...
3772   35000.0
5191   51000.0
5226   32000.0
5390   55000.0
860   100000.0

[5675 rows x 1 columns]

In [89]:
x_test

      kms_driven  owner   age  power  brand
7057     25500.0    1.0   5.0  390.0    8.0
5724    750000.0    1.0  10.0  100.0    5.0
2887     30862.0    1.0   5.0  180.0    4.0
3846       200.0    1.0   3.0  100.0    2.0
1172     56000.0    1.0   5.0  220.0    2.0
...          ...    ...   ...    ...    ...
4003     39500.0    1.0   8.0  220.0    2.0
1880      3594.0    1.0   3.0  310.0    4.0
2087     12510.0    1.0   4.0  150.0    5.0
181       7000.0    1.0   3.0  350.0    1.0
3592     36670.0    1.0   9.0  250.0    3.0

[1419 rows x 5 columns]

In [90]:
y_test

         price
7057  139100.0
5724   18000.0
2887   42000.0
3846   50000.0
1172   56000.0
...        ...
4003   44600.0
1880  200000.0
2087   45400.0
181   149000.0
3592   75000.0

[1419 rows x 1 columns]

In [91]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [92]:
pred=lr.predict(x_test)

In [93]:
pred

array([[243892.95311334],
       [-60821.64305038],
       [ 66177.22050261],
       ...,
       [ 68490.48368956],
       [127237.83651159],
       [ 79842.54743389]], shape=(1419, 1))

In [94]:
y_test

         price
7057  139100.0
5724   18000.0
2887   42000.0
3846   50000.0
1172   56000.0
...        ...
4003   44600.0
1880  200000.0
2087   45400.0
181   149000.0
3592   75000.0

[1419 rows x 1 columns]