In [2]:
! pip install pandas

Requirement already satisfied: pandas in C:\Users\rehan\OneDrive\Desktop\Data Science\boss\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\rehan\OneDrive\Desktop\Data Science\boss\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\rehan\OneDrive\Desktop\Data Science\boss\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\rehan\OneDrive\Desktop\Data Science\boss\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\rehan\OneDrive\Desktop\Data Science\boss\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import numpy as np
import pandas as pd
import os

In [4]:
student_data = {
    "Student_ID": [
        101, 102, 103, 104, 105,
        106, 107, 108, 109, 110,
        111, 112, 113, 114, 115,
        116, 117, 118, 119, 120
    ],
    "Student_Name": [
        "Aarav", "Vivaan", "Aditya", "Krishna", "Arjun",
        "Rohan", "Karan", "Rahul", "Mohit", "Ankit",
        "Priya", "Neha", "Pooja", "Sneha", "Riya",
        "Simran", "Kavya", "Isha", "Meera", "Aditi"
    ],
    "Marks": [
        85, 78, 92, 88, 76,
        81, 95, 67, 89, 73,
        91, 84, 79, 87, 93,
        75, 82, 90, 86, 80
    ]
}

In [ ]:
df=pd.DataFrame(student_data)  # create data frame from dictionary

In [ ]:
df['Student_Name']  # access column by name

0       Aarav
1      Vivaan
2      Aditya
3     Krishna
4       Arjun
5       Rohan
6       Karan
7       Rahul
8       Mohit
9       Ankit
10      Priya
11       Neha
12      Pooja
13      Sneha
14       Riya
15     Simran
16      Kavya
17       Isha
18      Meera
19      Aditi
Name: Student_Name, dtype: str

In [ ]:
df[['Student_Name']]  # access column by name and return as dataframe

   Student_Name
0         Aarav
1        Vivaan
2        Aditya
3       Krishna
4         Arjun
5         Rohan
6         Karan
7         Rahul
8         Mohit
9         Ankit
10        Priya
11         Neha
12        Pooja
13        Sneha
14         Riya
15       Simran
16        Kavya
17         Isha
18        Meera
19        Aditi

In [ ]:
df['Student_ID']  # access column by name and return as series

0     101
1     102
2     103
3     104
4     105
5     106
6     107
7     108
8     109
9     110
10    111
11    112
12    113
13    114
14    115
15    116
16    117
17    118
18    119
19    120
Name: Student_ID, dtype: int64

In [9]:
df.head(10)   # find upper 10 data

   Student_ID Student_Name  Marks
0         101        Aarav     85
1         102       Vivaan     78
2         103       Aditya     92
3         104      Krishna     88
4         105        Arjun     76
5         106        Rohan     81
6         107        Karan     95
7         108        Rahul     67
8         109        Mohit     89
9         110        Ankit     73

In [10]:
df.tail()  # next lower

    Student_ID Student_Name  Marks
15         116       Simran     75
16         117        Kavya     82
17         118         Isha     90
18         119        Meera     86
19         120        Aditi     80

In [ ]:
df.info()   # data set type and null value

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Student_ID    20 non-null     int64
 1   Student_Name  20 non-null     str
 2   Marks         20 non-null     int64
dtypes: int64(2), str(1)
memory usage: 612.0 bytes

In [ ]:
df.columns   # column name

Index(['Student_ID', 'Student_Name', 'Marks'], dtype='str')

In [ ]:
df[['Marks']]  # access column by name

    Marks
0      85
1      78
2      92
3      88
4      76
5      81
6      95
7      67
8      89
9      73
10     91
11     84
12     79
13     87
14     93
15     75
16     82
17     90
18     86
19     80

In [ ]:
df.drop('Student_ID',axis=1)   # drop column by name

   Student_Name  Marks
0         Aarav     85
1        Vivaan     78
2        Aditya     92
3       Krishna     88
4         Arjun     76
5         Rohan     81
6         Karan     95
7         Rahul     67
8         Mohit     89
9         Ankit     73
10        Priya     91
11         Neha     84
12        Pooja     79
13        Sneha     87
14         Riya     93
15       Simran     75
16        Kavya     82
17         Isha     90
18        Meera     86
19        Aditi     80

In [15]:
# df.drop('Student_ID',axis=1,inplace=True)  # drop column parmanently

In [ ]:
df=pd.read_csv('Used_Bikes.csv')  # read csv file and create data frame

In [ ]:
df  # print data frame

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [ ]:
df.head(5)  # print upper 5 data

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha

In [ ]:
df.tail(8)  # print lower 8 data

,bike_name,price,city,kms_driven,owner,age,power,brand
32640,Hero Passion Pro 100cc,32000.0,Delhi,12000.0,First Owner,6.0,100.0,Hero
32641,Bajaj Avenger 220cc,41000.0,Delhi,20245.0,Second Owner,11.0,220.0,Bajaj
32642,Hero Passion 100cc,15000.0,Perumbavoor,35000.0,Second Owner,19.0,100.0,Hero
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [ ]:
df.brand  # print brand access column by name

0                  TVS
1        Royal Enfield
2              Triumph
3                  TVS
4               Yamaha
             ...
32643             Hero
32644              TVS
32645            Bajaj
32646             Hero
32647            Bajaj
Name: brand, Length: 32648, dtype: str

In [ ]:
df[['brand']]  # print brand access column by name

               brand
0                TVS
1      Royal Enfield
2            Triumph
3                TVS
4             Yamaha
...              ...
32643           Hero
32644            TVS
32645          Bajaj
32646           Hero
32647          Bajaj

[32648 rows x 1 columns]

In [ ]:
df.bike_name  # print bike name

0          TVS Star City Plus Dual Tone 110cc
1                 Royal Enfield Classic 350cc
2                        Triumph Daytona 675R
3                        TVS Apache RTR 180cc
4        Yamaha FZ S V 2.0 150cc-Ltd. Edition
                         ...
32643                  Hero Passion Pro 100cc
32644                    TVS Apache RTR 180cc
32645                Bajaj Avenger Street 220
32646               Hero Super Splendor 125cc
32647                      Bajaj Pulsar 150cc
Name: bike_name, Length: 32648, dtype: str

In [ ]:
df['owner'].unique()  # unique value  ( no of unique value=nuniqu())

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [25]:
df[['brand']].value_counts()   #  no of avaliable bike

brand
Bajaj              11213
Hero                6368
Royal Enfield       4178
Yamaha              3916
Honda               2108
Suzuki              1464
TVS                 1247
KTM                 1077
Harley-Davidson      737
Kawasaki              79
Hyosung               64
Benelli               56
Mahindra              55
Triumph               26
Ducati                22
BMW                   16
Jawa                  10
MV                     4
Indian                 3
Ideal                  2
Rajdoot                1
LML                    1
Yezdi                  1
Name: count, dtype: int64

In [ ]:
df['brand'].nunique()  # no of unique brand

23

In [ ]:
df.duplicated()  # is duplicate value avaliable or not

0        False
1        False
2        False
3        False
4        False
         ...
32643     True
32644     True
32645     True
32646     True
32647     True
Length: 32648, dtype: bool

In [ ]:
df.duplicated().sum()  # no of duplicate value in data set

np.int64(25324)

In [ ]:
df.drop_duplicates()  # drop duplicate value  ( not permanently)

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [30]:
df.drop_duplicates(inplace=True)  # delete duplicate value parmanetly

In [ ]:
df.duplicated().sum()  # no of duplicate value

np.int64(0)

In [ ]:
df.isnull()

      bike_name  price   city  kms_driven  owner    age  power  brand
0         False  False  False       False  False  False  False  False
1         False  False  False       False  False  False  False  False
2         False  False  False       False  False  False  False  False
3         False  False  False       False  False  False  False  False
4         False  False  False       False  False  False  False  False
...         ...    ...    ...         ...    ...    ...    ...    ...
9362      False  False  False       False  False  False  False  False
9369      False  False  False       False  False  False  False  False
9370      False  False  False       False  False  False  False  False
9371      False  False  False       False  False  False  False  False
9372      False  False  False       False  False  False  False  False

[7324 rows x 8 columns]

In [ ]:
df.isnull().sum()

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64